# Generated by Django 6.0.4 on 2026-05-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['name'], 'verbose_name': 'Project category', 'verbose_name_plural': 'Project categories'},
        ),
    ]
